changelog:
  categories:
    - title: 🌱 What's new!
      labels:
        - feature
    - title: 🐆 Optimizations
      labels:
        - performance
    - title: 🛠️ Bugfixes
      labels:
        - bug
