# ⚠️  Find delightfully thorough documentation at https://goreleaser.com
version: 2
pro: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - main: ./cmd/reveald
    id: reveald
    binary: reveald
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: tar.gz
    id: reveald
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      reveald-
      {{- .Os }}-
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    builds: [reveald]
    format_overrides:
    - goos: windows
      format: zip
    # only embed binaries for now
    # https://goreleaser.com/customization/archive/?h=archives#packaging-only-the-binaries
    files:
    - none*

nfpms:
  - vendor: RunReveal Inc.
    homepage: https://runreveal.com
    license: Proprietary
    description: reveald is an all-in-one event ingestion daemon
    maintainer: RunReveal <contact@runreveal.com>
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    builds:
      - reveald

furies:
  - account: runreveal

changelog:
  use: github-native

# https://goreleaser.com/customization/release/
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: runreveal
    name: reveald

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-{{ .ShortCommit }}-{{ .Branch }}"

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
