package journald

import (
	"encoding/json"
	"testing"
)

func TestMessageJSONDetection(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name: "plain text message",
			input: `{
				"MESSAGE": "hello world",
				"__REALTIME_TIMESTAMP": "1234567890",
				"__CURSOR": "cursor123"
			}`,
			expected: `{
				"MESSAGE": {"text": "hello world"},
				"__REALTIME_TIMESTAMP": "1234567890",
				"__CURSOR": "cursor123"
			}`,
		},
		{
			name: "JSON object in string",
			input: `{
				"MESSAGE": "{\"key\":\"value\",\"number\":123}",
				"__REALTIME_TIMESTAMP": "1234567890",
				"__CURSOR": "cursor123"
			}`,
			expected: `{
				"MESSAGE": {"key":"value","number":123},
				"__REALTIME_TIMESTAMP": "1234567890",
				"__CURSOR": "cursor123",
				"_MESSAGE_IS_JSON": true
			}`,
		},
		{
			name: "JSON array in string",
			input: `{
				"MESSAGE": "[\"item1\",\"item2\",123]",
				"__REALTIME_TIMESTAMP": "1234567890",
				"__CURSOR": "cursor123"
			}`,
			expected: `{
				"MESSAGE": ["item1","item2",123],
				"__REALTIME_TIMESTAMP": "1234567890",
				"__CURSOR": "cursor123",
				"_MESSAGE_IS_JSON": true
			}`,
		},
		{
			name: "invalid JSON",
			input: `{
				"MESSAGE": "{invalid json",
				"__REALTIME_TIMESTAMP": "1234567890",
				"__CURSOR": "cursor123"
			}`,
			expected: `{
				"MESSAGE": {"text": "{invalid json"},
				"__REALTIME_TIMESTAMP": "1234567890",
				"__CURSOR": "cursor123"
			}`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var log autoGeneratedJournal
			if err := json.Unmarshal([]byte(tt.input), &log); err != nil {
				t.Fatalf("failed to unmarshal input: %v", err)
			}

			bts, err := transformMessageField([]byte(tt.input), log)
			if err != nil {
				t.Fatalf("transformMessageField failed: %v", err)
			}

			var result map[string]any
			if err := json.Unmarshal(bts, &result); err != nil {
				t.Fatalf("failed to unmarshal result: %v", err)
			}

			var expected map[string]any
			if err := json.Unmarshal([]byte(tt.expected), &expected); err != nil {
				t.Fatalf("failed to unmarshal expected: %v", err)
			}

			resultJSON, err := json.Marshal(result)
			if err != nil {
				t.Fatalf("failed to marshal result: %v", err)
			}
			expectedJSON, err := json.Marshal(expected)
			if err != nil {
				t.Fatalf("failed to marshal expected: %v", err)
			}

			if string(resultJSON) != string(expectedJSON) {
				t.Errorf("JSON mismatch:\nexpected: %s\ngot:      %s", string(expectedJSON), string(resultJSON))
			}
		})
	}
}
